// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://avlxadmsemdtiygbotas.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2bHhhZG1zZW1kdGl5Z2JvdGFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3OTcxNzQsImV4cCI6MjA1OTM3MzE3NH0.Uy397lqE2j6yU9dtNvkM5hNR28al_lBYv8gZQKhGRks";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);